name: mekato
description: "App de reservas de mesas - Mekato"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¥ Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_ui_auth: ^3.0.1

  # ğŸ” Autenticaciones sociales
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2

  # ğŸ¨ UI y animaciones
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
